<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE arboles [
        <!ELEMENT arboles (arbol)*>
        <!ELEMENT arbol (nombre|nombre_común|vegetación|altura|forma_y_estructura|color_en_primavera|color_en_otoño|resistencia_a_las_heladas)*>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT nombre_común (#PCDATA)>
        <!ELEMENT vegetación (#PCDATA)>
        <!ELEMENT altura (#PCDATA)>
        <!ELEMENT forma_y_estructura (#PCDATA)>
        <!ELEMENT color_en_primavera (#PCDATA)>
        <!ELEMENT color_en_otoño (#PCDATA)>
        <!ELEMENT resistencia_a_las_heladas (#PCDATA)>
        ]>
<arboles>
    <arbol>
        <nombre></nombre>
        <nombre_común></nombre_común>
        <vegetación></vegetación>
        <altura></altura>
        <forma_y_estructura></forma_y_estructura>
        <color_en_primavera></color_en_primavera>
        <color_en_otoño></color_en_otoño>
        <resistencia_a_las_heladas></resistencia_a_las_heladas>
    </arbol>
    <arbol>
        <nombre>Acer monspessulanum</nombre>
        <nombre_común>Arce de Montpellier, Arce menor</nombre_común>
        <vegetación>Caducifolio</vegetación>
        <altura>De 6 a 10 metros</altura>
        <forma_y_estructura>Copa esférica. Tronco principal recto con bifurcaciones. Ramaje colgante</forma_y_estructura>
        <color_en_primavera> Haz verde brillante, envés verde blanquecino</color_en_primavera>
        <resistencia_a_las_heladas>Heladas fuertes (hasta -15ºC)</resistencia_a_las_heladas>
    </arbol>
    <arbol>
        <nombre>Olea europea</nombre>
        <nombre_común>Olivo</nombre_común>
        <vegetación>Perenne</vegetación>
        <altura>De 8 a 15 metros</altura>
        <forma_y_estructura>Copa irregular. Tronco principal irregular con bifurcaciones</forma_y_estructura>
    </arbol>
    <arbol>
        <nombre>Ramaje tortuoso</nombre>
        <color_en_primavera>Haz verde oscuro, envés verde plateado</color_en_primavera>
        <resistencia_a_las_heladas>Heladas medias (hasta -10ºC)</resistencia_a_las_heladas>
    </arbol>
    <arbol>
        <nombre>Platanus orientalis</nombre>
        <nombre_común>Platano</nombre_común>
        <vegetación>Caducifolio</vegetación>
        <altura>De 20 a 25 metros</altura>
        <forma_y_estructura>Copa ovoidal. Tronco principal recto. Ramaje expandido</forma_y_estructura>
        <color_en_primavera> Haz verde medio, enves verde claro</color_en_primavera>
        <color_en_otoño>Ocre</color_en_otoño>
        <resistencia_a_las_heladas>Heladas fuertes (hasta -20ºC)</resistencia_a_las_heladas>
    </arbol>
    <arbol>
        <nombre>Quercus ilex</nombre>
        <nombre_común>Encina</nombre_común>
        <altura>En torno a 25 metros</altura>
        <forma_y_estructura>Copa esférica o elíptica irregular. Tronco principal recto. Ramaje tortuoso</forma_y_estructura>
        <color_en_primavera>Plateado en hojas jóvenes. En hojas antiguas, haz verde oscuro, envés plateado</color_en_primavera>
        <resistencia_a_las_heladas>Heladas fuertes (hasta -15ºC)</resistencia_a_las_heladas>
    </arbol>
</arboles>